project:
  type: website

website:
  title: "Binderiya Dugersuren"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Projects"
        menu:
          - text: "NYC Real Estate"
            href: "projects/project_NYC.qmd"
          - text: "US Job Trend Analysis"
            href: "projects/job_trend_analysis.qmd"
      - resume.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



